### ISSUE TITLE
Fails to compile if BMP is selected in Kconfig

### ISSUE THREAD

**Issue by cbaurtx** [utkumaden/esp-idf-bmx280#1] opened 2022-05-03 22:02 UTC
The bug is in the file bmx280_bits.h
The #ifndef CONFIG_BMX280_EXPECT_BMP280
is closed with #endif at the end of the file and not before
the #if !(CONFIG_BMX280_EXPECT_BMP280)
statement and this statement never will be executed

**Comment by utkumaden** [comment] 2022-05-04 07:26
I think I've mended the problem in [e1a0565](https://github.com/utkumaden/esp-idf-bmx280/commit/e1a05657e2a60e8b12e20c41752320327e8ebaeb). It built on my machine an please verify the issue is fixed before I close it.

Have fun coding and using the sensor.

**Comment by utkumaden** [comment] 2022-05-15 08:21
I'm closing this issue since I presume it was fixed with the latest changes and I got no response back.

**Closed as completed by utkumaden** 2022-05-15 08:21 UTC
